server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:my-ultra-secure-and-ultra-long-jwt-secret-key-tp3-microservices-2026-spring-boot}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:86400000}
