server.port=8081
spring.application.name=auth-service

# Segredo JWT compartilhado (min 256 bits) e tempos de expiração
jwt.secret=my-ultra-secure-and-ultra-long-jwt-secret-key-tp3-microservices-2026-spring-boot
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=86400000
